
**Name: Kausik Amancherla**

**Student ID: 002544017**

1) Create a cosine similarity matrix for all of Shakespeare’s works found in the provided le. This will result in a 42 by 42 matrix with the cosine similarity between each of his works. In other words, calculate the document-wise cosine similarity between all of Shakepeare’s works. Use TF_IDF for this. Note, you can use the Cosine Similarity function on scikit-learn or implement your own, but no other library/package is allowed.

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import linear_kernel
from sklearn.datasets import fetch_20newsgroups
import os, random
import numpy as np
import nltk
nltk.download('reuters')
nltk.download('punkt')

[nltk_data] Downloading package reuters to /root/nltk_data...
[nltk_data]   Package reuters is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [2]:
path = '/content/drive/MyDrive/shakespeares-works_TXT_FolgerShakespeare'

In [3]:
txt = os.listdir(path)

In [4]:
data = []
for f in txt :
  data.append(open(os.path.join(path,f), 'r').read())

tfidf = TfidfVectorizer()
matrix = tfidf.fit_transform(data)

In [5]:
Similarity_Matrix = cosine_similarity(matrix,matrix)
print(Similarity_Matrix)

[[1.         0.6106152  0.58915758 ... 0.59843788 0.71367332 0.69815654]
 [0.6106152  1.         0.49961181 ... 0.49330278 0.58762884 0.57264454]
 [0.58915758 0.49961181 1.         ... 0.47403783 0.5709058  0.55048388]
 ...
 [0.59843788 0.49330278 0.47403783 ... 1.         0.56273688 0.55511345]
 [0.71367332 0.58762884 0.5709058  ... 0.56273688 1.         0.66390227]
 [0.69815654 0.57264454 0.55048388 ... 0.55511345 0.66390227 1.        ]]


2) Write a function that takes the previous matrix and a number n as parameters (nothing else will be accepted) and return the top n similar works. Use the function to output the top 10 similar works.

In [6]:
def best_works(Similarity_Matrix, N):
  for i in range(len(Similarity_Matrix)):
    Similarity_Matrix[i][i] = 0 

  one_dimension = Similarity_Matrix.flatten().argsort()[-(2*N):]
  xrow, yrow = np.unravel_index(one_dimension, Similarity_Matrix.shape)
  xrow = np.flip(xrow)
  
  yrow = np.flip(yrow)
  top_10 = []

  for i in range(0,len(xrow),2):
    x = xrow[i]
    y = yrow[i]
    if(x != y):
      top_10.append((x,y,Similarity_Matrix[x][y]))
  return top_10

In [7]:
top_10 = best_works(Similarity_Matrix,10)

In [8]:
print(top_10)

[(7, 13, 0.9175430138884018), (6, 22, 0.9076165568984125), (35, 7, 0.8677688748875237), (25, 5, 0.8437915980298399), (16, 18, 0.8389525010107515), (13, 35, 0.838145210826978), (38, 4, 0.8363042342905279), (25, 15, 0.835492667018653), (25, 16, 0.8343507770652856), (4, 0, 0.8342954531999507)]


3) Using the code from the Language Models II class, train two simple language models using all of the less (together) in shakespeares-works_TXT_FolgerShakespeare.zip. One model should be trained using bigrams, the other using trigrams.

In [10]:
tokens = []
for doc in data:
  tokens.append(nltk.word_tokenize(doc))

We are going to use Bigrams :





In [11]:
from nltk.corpus import reuters
from nltk import bigrams, trigrams
from collections import Counter, defaultdict

In [12]:
bigram_model = defaultdict(lambda: defaultdict(lambda: 0))

for sentence in tokens:
    for w1, w2 in bigrams(sentence, pad_right=True, pad_left=True):
        bigram_model[w1][w2] += 1

In [13]:
for w1 in bigram_model:
    total_count = float(sum(bigram_model[w1].values()))
    for w2 in bigram_model[w1]:
        bigram_model[w1][w2] /= total_count

In [14]:
dict(bigram_model["King"])

{'!': 0.011428571428571429,
 "''": 0.0016326530612244899,
 "'s": 0.09551020408163265,
 ',': 0.11836734693877551,
 '--': 0.0024489795918367346,
 '.': 0.08897959183673469,
 ':': 0.004081632653061225,
 ';': 0.004081632653061225,
 '?': 0.0236734693877551,
 'And': 0.006530612244897959,
 'Be': 0.0008163265306122449,
 'Bolingbroke': 0.0008163265306122449,
 'Brothers': 0.0008163265306122449,
 'Cambyses': 0.0008163265306122449,
 'Capaneus': 0.0008163265306122449,
 'Cerberus': 0.0008163265306122449,
 'Claudius': 0.0008163265306122449,
 'Clothair': 0.0008163265306122449,
 'Cophetua': 0.0024489795918367346,
 'Digest': 0.0008163265306122449,
 'Dismiss': 0.0008163265306122449,
 'Does': 0.0008163265306122449,
 'Duncan': 0.0024489795918367346,
 'Edward': 0.027755102040816326,
 'Five': 0.0008163265306122449,
 'For': 0.0008163265306122449,
 'From': 0.0008163265306122449,
 'Gorboduc': 0.0008163265306122449,
 'Had': 0.0016326530612244899,
 'Hal': 0.0008163265306122449,
 'Hamlet': 0.0032653061224489797,
 '

We are going to use trigrams :



In [23]:
trigram_model = defaultdict(lambda: defaultdict(lambda: 0))

In [25]:
for sentence in tokens:
    for w1, w2, w3 in trigrams(sentence, pad_right=True, pad_left=True):
        trigram_model[(w1, w2)][w3] += 1

In [26]:
for w1_w2 in trigram_model:
    total_count = float(sum(trigram_model[w1_w2].values()))
    for w3 in trigram_model[w1_w2]:
        trigram_model[w1_w2][w3] /= total_count

In [27]:
dict(trigram_model["the","battle"])

{"'s": 0.06666666666666667,
 ',': 0.23333333333333334,
 '.': 0.1,
 'Which': 0.03333333333333333,
 'and': 0.06666666666666667,
 'came': 0.03333333333333333,
 'ends': 0.03333333333333333,
 'fly': 0.03333333333333333,
 "ha'": 0.03333333333333333,
 'let': 0.03333333333333333,
 'of': 0.03333333333333333,
 'range': 0.03333333333333333,
 'sought': 0.03333333333333333,
 'still': 0.03333333333333333,
 'than': 0.03333333333333333,
 'think': 0.06666666666666667,
 'thus': 0.06666666666666667,
 'to': 0.03333333333333333}

4) Write a function that takes the following three parameters: model, list of start words, number of sentences to generate. This function should return the sentences generated as a list. DO NOT print anything to the screen from within the function. Use this function to generate 10 sentences with the bigram model from the previous question, and 5 sentences with the trigram model from the previous question.

Bonus (20 points): Using the same methodology from questions 1 and 2, create a similarity matrix between the 20 newsgroups corpus. And nd the top 5 similar newsgroups.

In [28]:
new_newsgroups_data = fetch_20newsgroups()

In [29]:
tfidf = TfidfVectorizer()
matrix = tfidf.fit_transform(new_newsgroups_data.data)

Similarity_Matrix = cosine_similarity(matrix, matrix)
print(Similarity_Matrix)

[[1.         0.04405974 0.11017033 ... 0.04433678 0.04457107 0.0329325 ]
 [0.04405974 1.         0.06242113 ... 0.07373268 0.06959306 0.02439956]
 [0.11017033 0.06242113 1.         ... 0.07569182 0.06214891 0.02357985]
 ...
 [0.04433678 0.07373268 0.07569182 ... 1.         0.02909961 0.00716986]
 [0.04457107 0.06959306 0.06214891 ... 0.02909961 1.         0.02428174]
 [0.0329325  0.02439956 0.02357985 ... 0.00716986 0.02428174 1.        ]]


In [30]:
similar_works = best_works(Similarity_Matrix,10)
print(similar_works)

[(10777, 2002, 1.0000000000000002), (5392, 14, 1.0000000000000002), (9989, 800, 1.0), (4495, 4772, 0.9997809868890166), (8665, 4772, 0.9996809512865921), (981, 9920, 0.999622508768835), (8665, 4495, 0.9995302511028284), (4515, 4495, 0.9992512742959921), (4515, 4772, 0.9990101094182835), (4515, 8665, 0.9989914519713721)]
